db.people.insertMany([
  { id: 1, user_id: "user_abc", status: "A", age: 25 },
  { id: 2, user_id: "user_def", status: "B", age: 30 },
  { id: 3, user_id: "user_ghi", status: "C", age: 22 },
  { id: 4, user_id: "user_jkl", status: "D", age: 28 },
  { id: 5, user_id: "user_mno", status: "A", age: 55 },
  { id: 6, user_id: "user_pqr", status: "B", age: 40 },
  { id: 7, user_id: "user_stu", status: "C", age: 26 },
  { id: 8, user_id: "user_vwx", status: "D", age: 32 },
  { id: 9, user_id: "user_yza", status: "A", age: 24 },
  { id: 10, user_id: "user_bcd", status: "B", age: 29 },
  { id: 11, user_id: "user_efg", status: "C", age: 58 },
  { id: 12, user_id: "user_hij", status: "D", age: 33 },
  { id: 13, user_id: "user_klm", status: "A", age: 31 },
  { id: 14, user_id: "user_nop", status: "B", age: 23 },
  { id: 15, user_id: "user_qrs", status: "C", age: 34 },
  { id: 16, user_id: "user_tuv", status: "D", age: 21 },
  { id: 17, user_id: "user_wxy", status: "A", age: 50 },
  { id: 18, user_id: "user_zab", status: "B", age: 63 },
  { id: 19, user_id: "user_cde", status: "C", age: 39 },
  { id: 20, user_id: "user_fgh", status: "D", age: 50 },
]);
